name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-electron:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: "12"
    - name: Install dependencies
      run: npm i
    - name: Bundle app and build electron package
      run: npm run app:electron:build
